[metadata]
name = anchor_python
author = sics
description = the python driver for anchorbase
long_description = file: README.md
long_description_content_type = text/markdown
url = http://cod-git.sics.com/cod-x/anchor_python
python_requires = >=3.6
classifiers=
    Programming Language :: Python :: 3
    Programming Language :: C
    Topic :: Database
    Development Status :: 3 - Alpha
    Operating System :: OS Independent
    